/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mosaicofractal.gui;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractCellEditor;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import mosaicofractal.elementos.Preenchimento;
import mosaicofractal.tela.Tela;
import org.apache.batik.bridge.BridgeContext;
import org.apache.batik.bridge.GVTBuilder;
import org.apache.batik.gvt.GVTTreeWalker;
import org.apache.batik.gvt.GraphicsNode;
import static org.apache.batik.swing.svg.JSVGComponent.ALWAYS_DYNAMIC;
import org.w3c.dom.NodeList;
import org.w3c.dom.svg.SVGDocument;

/**
 *
 * @author Giordanna
 */
public class InterfaceUsuario extends javax.swing.JFrame {
    
    private Color cor_fundo_selecionada = Color.WHITE;
    private String textura = "textura1.svg";
    private String estampa = "estampa1.svg";
    private String forma_fundo = "estampa1.svg";
    private Dimension dim;
    private int quantidadeColunas, quantidadeLinhas;
    
    /**
     * Creates new form InterfaceUsuario
     */
    public InterfaceUsuario() {
        initComponents();
        dim = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(dim.width/2-getSize().width/2, dim.height/2-getSize().height/2);
        
        frameEstampaEscolher.pack();
        frameEstampaEscolher.setLocation(dim.width/2-frameEstampaEscolher.getSize().width/2, dim.height/2-frameEstampaEscolher.getSize().height/2);
        
        frameTexturasEscolher.pack();
        frameTexturasEscolher.setLocation(dim.width/2-frameTexturasEscolher.getSize().width/2, dim.height/2-frameTexturasEscolher.getSize().height/2);
        
        frameCoresEscolher.pack();
        frameCoresEscolher.setLocation(dim.width/2-frameCoresEscolher.getSize().width/2, dim.height/2-frameCoresEscolher.getSize().height/2);
        
        frameVerCores.pack();
        frameVerCores.setLocation(dim.width/2-frameVerCores.getSize().width/2, dim.height/2-frameVerCores.getSize().height/2);
        
        javax.swing.ImageIcon icone = new javax.swing.ImageIcon("./img/icones/icone_small.png");
        setIconImage(icone.getImage());
        frameTexturasEscolher.setIconImage(icone.getImage());
        frameEstampaEscolher.setIconImage(icone.getImage());
        frameCoresEscolher.setIconImage(icone.getImage());
        frameVerCores.setIconImage(icone.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupBordaTela = new javax.swing.ButtonGroup();
        buttonGroupRotacionarEstampas = new javax.swing.ButtonGroup();
        buttonGroupTelaForma = new javax.swing.ButtonGroup();
        buttonGroupTipoPreenchimento = new javax.swing.ButtonGroup();
        fileEstampaAdicionar = new javax.swing.JFileChooser();
        filePreenchimentoAdicionar = new javax.swing.JFileChooser();
        frameVerCores = new javax.swing.JFrame();
        tabelaVerCores = new javax.swing.JTable();
        frameEstampaEscolher = new javax.swing.JFrame();
        comboboxEstampas = new javax.swing.JComboBox<>();
        textoFrameEstampaCorpo = new javax.swing.JLabel();
        canvasframeEstampa = new org.apache.batik.swing.JSVGCanvas();
        botaoEstampaSelecionar = new javax.swing.JButton();
        botaoEstampaExcluir = new javax.swing.JButton();
        textoFrameEstampaPreview = new javax.swing.JLabel();
        botaoEstampaSelecionarFundo = new javax.swing.JButton();
        frameTexturasEscolher = new javax.swing.JFrame();
        comboboxTexturas = new javax.swing.JComboBox<>();
        textoFrameTexturaCorpo = new javax.swing.JLabel();
        canvasframeTextura = new org.apache.batik.swing.JSVGCanvas();
        botaoTexturaSelecionar = new javax.swing.JButton();
        botaoTexturaExcluir = new javax.swing.JButton();
        textoFrameTexturaPreview = new javax.swing.JLabel();
        frameCoresEscolher = new javax.swing.JFrame();
        textoFrameCoresCorpo = new javax.swing.JLabel();
        textoFrameCoresEstampas = new javax.swing.JLabel();
        textoFrameCoresFundo = new javax.swing.JLabel();
        panelFrameCoresFundo = new javax.swing.JPanel();
        botaoFrameCoresFundoSelecionar = new javax.swing.JButton();
        botaoVerCoresEscolher = new javax.swing.JButton();
        panelCorpo = new javax.swing.JPanel();
        textoValorC = new javax.swing.JLabel();
        spinnerValorC = new javax.swing.JSpinner();
        textoPreview = new javax.swing.JLabel();
        botaoIniciar = new javax.swing.JButton();
        textoBordaTela = new javax.swing.JLabel();
        radioBordaTelaSim = new javax.swing.JRadioButton();
        radioBordaTelaNao = new javax.swing.JRadioButton();
        textoRotacionarEstampas = new javax.swing.JLabel();
        radioRotacionarEstampasSim = new javax.swing.JRadioButton();
        radioRotacionarEstampasNao = new javax.swing.JRadioButton();
        textoTelaForma = new javax.swing.JLabel();
        radioTelaFormaSim = new javax.swing.JRadioButton();
        radioTelaFormaNao = new javax.swing.JRadioButton();
        textoTipoPreenchimento = new javax.swing.JLabel();
        radioTipoPreenchimentoCores = new javax.swing.JRadioButton();
        radioTipoPreenchimentoTexturas = new javax.swing.JRadioButton();
        panelSeparador = new javax.swing.JSeparator();
        canvasPreviewModo = new org.apache.batik.swing.JSVGCanvas();
        canvasPreviewPreenchimento = new org.apache.batik.swing.JSVGCanvas();
        textoPreviewModo = new javax.swing.JLabel();
        textoPreviewEstampa = new javax.swing.JLabel();
        textoPreviewPreenchimento = new javax.swing.JLabel();
        textoPreviewPreenchimentoCores = new javax.swing.JLabel();
        textoPreviewPreenchimentoTextura = new javax.swing.JLabel();
        canvasPreviewEstampa = new org.apache.batik.swing.JSVGCanvas();
        textoPreviewCorFundo = new javax.swing.JLabel();
        previewCorFundo = new javax.swing.JPanel();
        textoPreviewFormaFundo = new javax.swing.JLabel();
        canvasPreviewFormaFundo = new org.apache.batik.swing.JSVGCanvas();
        textoQuantidadeFormas = new javax.swing.JLabel();
        spinnerQuantidadeFormas = new javax.swing.JSpinner();
        textoIteracoes = new javax.swing.JLabel();
        spinnerIteracoes = new javax.swing.JSpinner();
        botaoVerCores = new javax.swing.JButton();
        textoTitulo = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuEstampas = new javax.swing.JMenu();
        estampaAdicionar = new javax.swing.JMenuItem();
        estampaSelecionar = new javax.swing.JMenuItem();
        menuPreenchimento = new javax.swing.JMenu();
        menuCores = new javax.swing.JMenu();
        itemCoresSelecionar = new javax.swing.JMenuItem();
        menuTextura = new javax.swing.JMenu();
        itemTexturaAdicionar = new javax.swing.JMenuItem();
        itemTexturaSelecionar = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        itemManual = new javax.swing.JMenuItem();
        itemSobre = new javax.swing.JMenuItem();

        fileEstampaAdicionar.setFileFilter(new FileNameExtensionFilter("SVG", "svg"));

        filePreenchimentoAdicionar.setFileFilter(new FileNameExtensionFilter("SVG", "svg"));

        frameVerCores.setTitle("Visualização de cores");
        frameVerCores.setResizable(false);

        tabelaVerCores.setBackground(javax.swing.UIManager.getDefaults().getColor("TextField.disabledBackground"));
        tabelaVerCores.setModel(new modeloTabelaCores());
        tabelaVerCores.setDefaultRenderer(Color.class, new RenderizadorDeCor(true));
        tabelaVerCores.setDefaultEditor(Color.class, new editorDeCor());
        quantidadeColunas = tabelaVerCores.getModel().getColumnCount();
        quantidadeLinhas = tabelaVerCores.getModel().getRowCount();

        javax.swing.GroupLayout frameVerCoresLayout = new javax.swing.GroupLayout(frameVerCores.getContentPane());
        frameVerCores.getContentPane().setLayout(frameVerCoresLayout);
        frameVerCoresLayout.setHorizontalGroup(
            frameVerCoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameVerCoresLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tabelaVerCores, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        frameVerCoresLayout.setVerticalGroup(
            frameVerCoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameVerCoresLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tabelaVerCores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        frameEstampaEscolher.setTitle("Escolher Estampas");
        frameEstampaEscolher.setResizable(false);
        frameEstampaEscolher.setType(java.awt.Window.Type.POPUP);

        comboboxEstampas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "estampa1.svg", "estampa2.svg" }));
        comboboxEstampas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxEstampasActionPerformed(evt);
            }
        });

        textoFrameEstampaCorpo.setText("Escolha uma das estampas disponíveis e selecione a sua opção desejada:");

        canvasframeEstampa.setBackground(java.awt.SystemColor.control);
        canvasframeEstampa.setEnableImageZoomInteractor(false);
        canvasframeEstampa.setEnablePanInteractor(false);
        canvasframeEstampa.setEnableResetTransformInteractor(false);
        canvasframeEstampa.setEnableRotateInteractor(false);
        canvasframeEstampa.setEnableZoomInteractor(false);
        canvasframeEstampa.setPreferredSize(new java.awt.Dimension(150, 150));

        try{
            File g = new File("img/estampas/estampa1.svg").getCanonicalFile();
            canvasframeEstampa.setURI(g.toURI().toString());
        }
        catch(java.io.IOException e){
        }

        botaoEstampaSelecionar.setText("Selecionar como Estampa");
        botaoEstampaSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEstampaSelecionarActionPerformed(evt);
            }
        });

        botaoEstampaExcluir.setText("Excluir Arquivo");
        botaoEstampaExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEstampaExcluirActionPerformed(evt);
            }
        });

        textoFrameEstampaPreview.setText("Preview:");

        botaoEstampaSelecionarFundo.setText("Selecionar como Fundo");
        botaoEstampaSelecionarFundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEstampaSelecionarFundoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameEstampaEscolherLayout = new javax.swing.GroupLayout(frameEstampaEscolher.getContentPane());
        frameEstampaEscolher.getContentPane().setLayout(frameEstampaEscolherLayout);
        frameEstampaEscolherLayout.setHorizontalGroup(
            frameEstampaEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameEstampaEscolherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameEstampaEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textoFrameEstampaCorpo)
                    .addGroup(frameEstampaEscolherLayout.createSequentialGroup()
                        .addGroup(frameEstampaEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frameEstampaEscolherLayout.createSequentialGroup()
                                .addComponent(comboboxEstampas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textoFrameEstampaPreview)
                                .addGap(18, 18, 18))
                            .addGroup(frameEstampaEscolherLayout.createSequentialGroup()
                                .addGroup(frameEstampaEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoEstampaSelecionar)
                                    .addComponent(botaoEstampaSelecionarFundo)
                                    .addComponent(botaoEstampaExcluir))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(canvasframeEstampa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frameEstampaEscolherLayout.setVerticalGroup(
            frameEstampaEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameEstampaEscolherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoFrameEstampaCorpo)
                .addGap(18, 18, 18)
                .addGroup(frameEstampaEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(frameEstampaEscolherLayout.createSequentialGroup()
                        .addGroup(frameEstampaEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboboxEstampas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoFrameEstampaPreview))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoEstampaSelecionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoEstampaSelecionarFundo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoEstampaExcluir))
                    .addComponent(canvasframeEstampa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        frameTexturasEscolher.setTitle("Escolher Texturas");
        frameTexturasEscolher.setResizable(false);

        comboboxTexturas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "textura1.svg" }));
        comboboxTexturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxTexturasActionPerformed(evt);
            }
        });

        textoFrameTexturaCorpo.setText("Escolha uma das texturas disponíveis e selecione a sua opção desejada:");

        canvasframeTextura.setBackground(java.awt.SystemColor.control);
        canvasframeTextura.setEnableImageZoomInteractor(false);
        canvasframeTextura.setEnablePanInteractor(false);
        canvasframeTextura.setEnableResetTransformInteractor(false);
        canvasframeTextura.setEnableRotateInteractor(false);
        canvasframeTextura.setEnableZoomInteractor(false);
        canvasframeTextura.setPreferredSize(new java.awt.Dimension(150, 150));

        try{
            File g = new File("img/texturas/textura1.svg").getCanonicalFile();
            canvasframeTextura.setURI(g.toURI().toString());
        }
        catch(java.io.IOException e){
        }

        botaoTexturaSelecionar.setText("Selecionar");
        botaoTexturaSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTexturaSelecionarActionPerformed(evt);
            }
        });

        botaoTexturaExcluir.setText("Excluir");
        botaoTexturaExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTexturaExcluirActionPerformed(evt);
            }
        });

        textoFrameTexturaPreview.setText("Preview:");

        javax.swing.GroupLayout frameTexturasEscolherLayout = new javax.swing.GroupLayout(frameTexturasEscolher.getContentPane());
        frameTexturasEscolher.getContentPane().setLayout(frameTexturasEscolherLayout);
        frameTexturasEscolherLayout.setHorizontalGroup(
            frameTexturasEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameTexturasEscolherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameTexturasEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(frameTexturasEscolherLayout.createSequentialGroup()
                        .addComponent(textoFrameTexturaCorpo)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(frameTexturasEscolherLayout.createSequentialGroup()
                        .addGroup(frameTexturasEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frameTexturasEscolherLayout.createSequentialGroup()
                                .addComponent(botaoTexturaSelecionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoTexturaExcluir))
                            .addGroup(frameTexturasEscolherLayout.createSequentialGroup()
                                .addComponent(comboboxTexturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textoFrameTexturaPreview)))
                        .addGap(18, 18, 18)
                        .addComponent(canvasframeTextura, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        frameTexturasEscolherLayout.setVerticalGroup(
            frameTexturasEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameTexturasEscolherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoFrameTexturaCorpo)
                .addGap(18, 18, 18)
                .addGroup(frameTexturasEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(frameTexturasEscolherLayout.createSequentialGroup()
                        .addGroup(frameTexturasEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboboxTexturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoFrameTexturaPreview))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(frameTexturasEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoTexturaSelecionar)
                            .addComponent(botaoTexturaExcluir)))
                    .addComponent(canvasframeTextura, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        frameCoresEscolher.setTitle("Escolher Cores");
        frameCoresEscolher.setResizable(false);

        textoFrameCoresCorpo.setText("Escolha as cores desejadas:");

        textoFrameCoresEstampas.setText("Estampas:");

        textoFrameCoresFundo.setText("Para o fundo:");

        panelFrameCoresFundo.setBackground(new java.awt.Color(255, 255, 255));
        panelFrameCoresFundo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelFrameCoresFundoLayout = new javax.swing.GroupLayout(panelFrameCoresFundo);
        panelFrameCoresFundo.setLayout(panelFrameCoresFundoLayout);
        panelFrameCoresFundoLayout.setHorizontalGroup(
            panelFrameCoresFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelFrameCoresFundoLayout.setVerticalGroup(
            panelFrameCoresFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        botaoFrameCoresFundoSelecionar.setText("Selecionar");
        botaoFrameCoresFundoSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFrameCoresFundoSelecionarActionPerformed(evt);
            }
        });

        botaoVerCoresEscolher.setText("Ver Cores");
        botaoVerCoresEscolher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVerCoresEscolherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameCoresEscolherLayout = new javax.swing.GroupLayout(frameCoresEscolher.getContentPane());
        frameCoresEscolher.getContentPane().setLayout(frameCoresEscolherLayout);
        frameCoresEscolherLayout.setHorizontalGroup(
            frameCoresEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameCoresEscolherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameCoresEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameCoresEscolherLayout.createSequentialGroup()
                        .addGroup(frameCoresEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoFrameCoresCorpo)
                            .addComponent(textoFrameCoresEstampas)
                            .addComponent(textoFrameCoresFundo)
                            .addGroup(frameCoresEscolherLayout.createSequentialGroup()
                                .addComponent(panelFrameCoresFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoFrameCoresFundoSelecionar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(botaoVerCoresEscolher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        frameCoresEscolherLayout.setVerticalGroup(
            frameCoresEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameCoresEscolherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoFrameCoresCorpo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoFrameCoresEstampas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(botaoVerCoresEscolher)
                .addGap(18, 18, 18)
                .addComponent(textoFrameCoresFundo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameCoresEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFrameCoresFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoFrameCoresFundoSelecionar)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mosaico Fractal");
        setResizable(false);

        textoValorC.setText("Valor de c:");

        spinnerValorC.setModel(new javax.swing.SpinnerNumberModel(1.48d, 1.0d, 1.48d, 0.01d));

        textoPreview.setText("Preview:");

        botaoIniciar.setText("Iniciar");
        botaoIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIniciarActionPerformed(evt);
            }
        });

        textoBordaTela.setText("Considerar as bordas da tela como limites do mosaico?");

        buttonGroupBordaTela.add(radioBordaTelaSim);
        radioBordaTelaSim.setSelected(true);
        radioBordaTelaSim.setText("Sim");
        radioBordaTelaSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBordaTelaSimActionPerformed(evt);
            }
        });

        buttonGroupBordaTela.add(radioBordaTelaNao);
        radioBordaTelaNao.setText("Não");
        radioBordaTelaNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBordaTelaNaoActionPerformed(evt);
            }
        });

        textoRotacionarEstampas.setText("Rotacionar as estampas aleatoriamente?");

        buttonGroupRotacionarEstampas.add(radioRotacionarEstampasSim);
        radioRotacionarEstampasSim.setText("Sim");
        radioRotacionarEstampasSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRotacionarEstampasSimActionPerformed(evt);
            }
        });

        buttonGroupRotacionarEstampas.add(radioRotacionarEstampasNao);
        radioRotacionarEstampasNao.setSelected(true);
        radioRotacionarEstampasNao.setText("Não");
        radioRotacionarEstampasNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRotacionarEstampasNaoActionPerformed(evt);
            }
        });

        textoTelaForma.setText("A tela terá uma forma específica?");

        buttonGroupTelaForma.add(radioTelaFormaSim);
        radioTelaFormaSim.setText("Sim");
        radioTelaFormaSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTelaFormaSimActionPerformed(evt);
            }
        });

        buttonGroupTelaForma.add(radioTelaFormaNao);
        radioTelaFormaNao.setSelected(true);
        radioTelaFormaNao.setText("Não");
        radioTelaFormaNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTelaFormaNaoActionPerformed(evt);
            }
        });

        textoTipoPreenchimento.setText("O que será usado como preenchimento?");

        buttonGroupTipoPreenchimento.add(radioTipoPreenchimentoCores);
        radioTipoPreenchimentoCores.setSelected(true);
        radioTipoPreenchimentoCores.setText("Cores");
        radioTipoPreenchimentoCores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTipoPreenchimentoCoresActionPerformed(evt);
            }
        });

        buttonGroupTipoPreenchimento.add(radioTipoPreenchimentoTexturas);
        radioTipoPreenchimentoTexturas.setText("Texturas");
        radioTipoPreenchimentoTexturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTipoPreenchimentoTexturasActionPerformed(evt);
            }
        });

        canvasPreviewModo.setBackground(new java.awt.Color(240, 240, 240));
        canvasPreviewModo.setEnableImageZoomInteractor(false);
        canvasPreviewModo.setEnablePanInteractor(false);
        canvasPreviewModo.setEnableResetTransformInteractor(false);
        canvasPreviewModo.setEnableRotateInteractor(false);
        canvasPreviewModo.setEnableZoomInteractor(false);
        canvasPreviewModo.setPreferredSize(new java.awt.Dimension(100, 100));

        try{
            File g = new File("img/icones/modo_sem_forma_nao_rotaciona_com_limite.svg").getCanonicalFile();
            canvasPreviewModo.setURI(g.toURI().toString());
        }
        catch(java.io.IOException e){
        }

        canvasPreviewPreenchimento.setBackground(new java.awt.Color(240, 240, 240));
        canvasPreviewPreenchimento.setDocumentState(ALWAYS_DYNAMIC);
        canvasPreviewPreenchimento.setEnableImageZoomInteractor(false);
        canvasPreviewPreenchimento.setEnablePanInteractor(false);
        canvasPreviewPreenchimento.setEnableResetTransformInteractor(false);
        canvasPreviewPreenchimento.setEnableRotateInteractor(false);
        canvasPreviewPreenchimento.setEnableZoomInteractor(false);
        canvasPreviewPreenchimento.setPreferredSize(new java.awt.Dimension(100, 100));

        textoPreviewModo.setText("Modo:");

        textoPreviewEstampa.setText("Estampa(s):");

        textoPreviewPreenchimento.setText("Preenchimento:");

        textoPreviewPreenchimentoCores.setText("Cores? Sim. Sendo elas:");

        textoPreviewPreenchimentoTextura.setForeground(java.awt.SystemColor.textInactiveText);
        textoPreviewPreenchimentoTextura.setText("Textura? Não.");

        canvasPreviewEstampa.setBackground(new java.awt.Color(240, 240, 240));
        canvasPreviewEstampa.setDocument(null);
        canvasPreviewEstampa.setDocumentState(ALWAYS_DYNAMIC);
        canvasPreviewEstampa.setEnableImageZoomInteractor(false);
        canvasPreviewEstampa.setEnablePanInteractor(false);
        canvasPreviewEstampa.setEnableResetTransformInteractor(false);
        canvasPreviewEstampa.setEnableRotateInteractor(false);
        canvasPreviewEstampa.setEnableZoomInteractor(false);
        canvasPreviewEstampa.setPreferredSize(new java.awt.Dimension(100, 100));

        try{
            File g = new File("img/estampas/estampa1.svg").getCanonicalFile();
            canvasPreviewEstampa.setURI(g.toURI().toString());
        }
        catch(java.io.IOException e){
        }

        textoPreviewCorFundo.setText("Cor do Fundo:");

        previewCorFundo.setBackground(new java.awt.Color(255, 255, 255));
        previewCorFundo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        previewCorFundo.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout previewCorFundoLayout = new javax.swing.GroupLayout(previewCorFundo);
        previewCorFundo.setLayout(previewCorFundoLayout);
        previewCorFundoLayout.setHorizontalGroup(
            previewCorFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        previewCorFundoLayout.setVerticalGroup(
            previewCorFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        textoPreviewFormaFundo.setText("Fundo normal.");

        canvasPreviewFormaFundo.setBackground(new java.awt.Color(240, 240, 240));
        canvasPreviewFormaFundo.setDocumentState(ALWAYS_DYNAMIC);
        canvasPreviewFormaFundo.setEnableImageZoomInteractor(false);
        canvasPreviewFormaFundo.setEnablePanInteractor(false);
        canvasPreviewFormaFundo.setEnableResetTransformInteractor(false);
        canvasPreviewFormaFundo.setEnableRotateInteractor(false);
        canvasPreviewFormaFundo.setEnableZoomInteractor(false);
        canvasPreviewFormaFundo.setPreferredSize(new java.awt.Dimension(100, 100));

        textoQuantidadeFormas.setText("Quantidade de formas:");

        spinnerQuantidadeFormas.setModel(new javax.swing.SpinnerNumberModel(1000, 10, 90000, 1));

        textoIteracoes.setText("Iterações:");

        spinnerIteracoes.setModel(new javax.swing.SpinnerNumberModel(1000, 100, 400000, 1));

        botaoVerCores.setText("Ver Cores");
        botaoVerCores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVerCoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCorpoLayout = new javax.swing.GroupLayout(panelCorpo);
        panelCorpo.setLayout(panelCorpoLayout);
        panelCorpoLayout.setHorizontalGroup(
            panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCorpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSeparador)
                    .addGroup(panelCorpoLayout.createSequentialGroup()
                        .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCorpoLayout.createSequentialGroup()
                                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoPreviewModo)
                                    .addComponent(canvasPreviewModo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(canvasPreviewEstampa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoPreviewEstampa))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoPreviewFormaFundo)
                                    .addComponent(canvasPreviewFormaFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoPreviewPreenchimento)
                                    .addGroup(panelCorpoLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textoPreviewPreenchimentoCores)
                                            .addComponent(textoPreviewPreenchimentoTextura)
                                            .addComponent(textoPreviewCorFundo)
                                            .addComponent(previewCorFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(botaoVerCores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(6, 6, 6)
                                .addComponent(canvasPreviewPreenchimento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCorpoLayout.createSequentialGroup()
                                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelCorpoLayout.createSequentialGroup()
                                        .addComponent(radioTelaFormaSim)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioTelaFormaNao))
                                    .addGroup(panelCorpoLayout.createSequentialGroup()
                                        .addComponent(radioRotacionarEstampasSim)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioRotacionarEstampasNao))
                                    .addComponent(textoBordaTela)
                                    .addGroup(panelCorpoLayout.createSequentialGroup()
                                        .addComponent(radioBordaTelaSim)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioBordaTelaNao))
                                    .addComponent(textoRotacionarEstampas)
                                    .addComponent(textoTelaForma)
                                    .addComponent(textoTipoPreenchimento)
                                    .addGroup(panelCorpoLayout.createSequentialGroup()
                                        .addComponent(radioTipoPreenchimentoCores)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioTipoPreenchimentoTexturas))
                                    .addComponent(textoPreview)
                                    .addComponent(botaoIniciar)
                                    .addGroup(panelCorpoLayout.createSequentialGroup()
                                        .addComponent(textoValorC)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spinnerValorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textoQuantidadeFormas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spinnerQuantidadeFormas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textoIteracoes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spinnerIteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        panelCorpoLayout.setVerticalGroup(
            panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCorpoLayout.createSequentialGroup()
                .addComponent(textoBordaTela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBordaTelaSim)
                    .addComponent(radioBordaTelaNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoRotacionarEstampas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioRotacionarEstampasSim)
                    .addComponent(radioRotacionarEstampasNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoTelaForma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioTelaFormaSim)
                    .addComponent(radioTelaFormaNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoTipoPreenchimento, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioTipoPreenchimentoCores)
                    .addComponent(radioTipoPreenchimentoTexturas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoValorC)
                    .addComponent(spinnerValorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoQuantidadeFormas)
                    .addComponent(spinnerQuantidadeFormas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoIteracoes)
                    .addComponent(spinnerIteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoIniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoPreview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPreviewModo)
                    .addComponent(textoPreviewEstampa)
                    .addComponent(textoPreviewPreenchimento)
                    .addComponent(textoPreviewFormaFundo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canvasPreviewModo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canvasPreviewPreenchimento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canvasPreviewEstampa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCorpoLayout.createSequentialGroup()
                        .addComponent(textoPreviewPreenchimentoCores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoVerCores)
                        .addGap(3, 3, 3)
                        .addComponent(textoPreviewPreenchimentoTextura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoPreviewCorFundo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previewCorFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(canvasPreviewFormaFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textoTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoTitulo.setText("Mosaico Fractal");

        menuEstampas.setText("Estampas");

        estampaAdicionar.setText("Adicionar...");
        estampaAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estampaAdicionarActionPerformed(evt);
            }
        });
        menuEstampas.add(estampaAdicionar);

        estampaSelecionar.setText("Selecionar...");
        estampaSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estampaSelecionarActionPerformed(evt);
            }
        });
        menuEstampas.add(estampaSelecionar);

        barraMenu.add(menuEstampas);

        menuPreenchimento.setText("Preenchimento");

        menuCores.setText("Cores");

        itemCoresSelecionar.setText("Selecionar...");
        itemCoresSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCoresSelecionarActionPerformed(evt);
            }
        });
        menuCores.add(itemCoresSelecionar);

        menuPreenchimento.add(menuCores);

        menuTextura.setText("Textura");

        itemTexturaAdicionar.setText("Adicionar...");
        itemTexturaAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTexturaAdicionarActionPerformed(evt);
            }
        });
        menuTextura.add(itemTexturaAdicionar);

        itemTexturaSelecionar.setText("Selecionar...");
        itemTexturaSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTexturaSelecionarActionPerformed(evt);
            }
        });
        menuTextura.add(itemTexturaSelecionar);

        menuPreenchimento.add(menuTextura);

        barraMenu.add(menuPreenchimento);

        menuAjuda.setText("Ajuda");

        itemManual.setText("Manual");
        menuAjuda.add(itemManual);

        itemSobre.setText("Sobre");
        menuAjuda.add(itemSobre);

        barraMenu.add(menuAjuda);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCorpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoTitulo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(textoTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCorpo, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioTelaFormaSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTelaFormaSimActionPerformed
        if (!radioBordaTelaSim.isSelected()){
            radioBordaTelaSim.setSelected(true);
        }
        if (radioTelaFormaSim.isSelected()) {
            if (radioRotacionarEstampasSim.isSelected()) {
                trocaPreviewIconeModo("modo_com_forma_sim_rotaciona");
            }
            else {
                trocaPreviewIconeModo("modo_com_forma_nao_rotaciona");
            }
        }
        textoPreviewFormaFundo.setText("Forma do fundo:");
        trocaIconeEstampa(canvasPreviewFormaFundo, forma_fundo);
    }//GEN-LAST:event_radioTelaFormaSimActionPerformed

    private void radioBordaTelaNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBordaTelaNaoActionPerformed
        if (!radioTelaFormaNao.isSelected()){
            radioTelaFormaNao.setSelected(true);
            textoPreviewFormaFundo.setText("Fundo normal.");
            deixaVazio(canvasPreviewFormaFundo);
        }
        if (radioBordaTelaNao.isSelected()) {
            if (radioRotacionarEstampasSim.isSelected()) {
                trocaPreviewIconeModo("modo_sem_forma_sim_rotaciona_sem_limite");
            }
            else {
                trocaPreviewIconeModo("modo_sem_forma_nao_rotaciona_sem_limite");
            }
        }
    }//GEN-LAST:event_radioBordaTelaNaoActionPerformed

    private void radioTelaFormaNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTelaFormaNaoActionPerformed
        if (radioTelaFormaNao.isSelected()) {
            if (radioRotacionarEstampasSim.isSelected()) {
                if (radioBordaTelaSim.isSelected()) {
                    trocaPreviewIconeModo("modo_sem_forma_sim_rotaciona_com_limite");
                }
                else {
                    trocaPreviewIconeModo("modo_sem_forma_sim_rotaciona_sem_limite");
                }
            }
            else {
                if (radioBordaTelaSim.isSelected()) {
                    trocaPreviewIconeModo("modo_sem_forma_nao_rotaciona_com_limite");
                }
                else {
                    trocaPreviewIconeModo("modo_sem_forma_nao_rotaciona_sem_limite");
                }
            }
        }
        textoPreviewFormaFundo.setText("Fundo normal.");
        deixaVazio(canvasPreviewFormaFundo);
    }//GEN-LAST:event_radioTelaFormaNaoActionPerformed

    private void radioTipoPreenchimentoCoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTipoPreenchimentoCoresActionPerformed
        if (!"Cores? Sim. Sendo elas:".equals(textoPreviewPreenchimentoCores.getText())){
            textoPreviewPreenchimentoCores.setText("Cores? Sim. Sendo elas:");
            textoPreviewPreenchimentoCores.setForeground(java.awt.Color.BLACK);
            botaoVerCores.setVisible(true);
        }
        if ("Textura? Sim. Sendo ela:".equals(textoPreviewPreenchimentoTextura.getText())){
            textoPreviewPreenchimentoTextura.setText("Textura? Não.");
            textoPreviewPreenchimentoTextura.setForeground(java.awt.SystemColor.textInactiveText);
            deixaVazio(canvasPreviewPreenchimento);
        }
    }//GEN-LAST:event_radioTipoPreenchimentoCoresActionPerformed

    private void radioTipoPreenchimentoTexturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTipoPreenchimentoTexturasActionPerformed
        if ("Cores? Sim. Sendo elas:".equals(textoPreviewPreenchimentoCores.getText())){
            textoPreviewPreenchimentoCores.setText("Cores? Não.");
            textoPreviewPreenchimentoCores.setForeground(java.awt.SystemColor.textInactiveText);
            botaoVerCores.setVisible(false);
        }
        if (!"Textura? Sim. Sendo ela:".equals(textoPreviewPreenchimentoTextura.getText())){
            textoPreviewPreenchimentoTextura.setText("Textura? Sim. Sendo ela:");
            textoPreviewPreenchimentoTextura.setForeground(java.awt.Color.BLACK);
        }
        
        trocaIconeTextura(canvasPreviewPreenchimento, textura);
    }//GEN-LAST:event_radioTipoPreenchimentoTexturasActionPerformed

    private void radioBordaTelaSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBordaTelaSimActionPerformed
        if (radioBordaTelaSim.isSelected()) {
            if (radioTelaFormaSim.isSelected()) {
                if (radioRotacionarEstampasSim.isSelected()) {
                    trocaPreviewIconeModo("modo_com_forma_sim_rotaciona");
                }
                else {
                    trocaPreviewIconeModo("modo_com_forma_nao_rotaciona");
                }
            }
            else {
                if (radioRotacionarEstampasSim.isSelected()) {
                    trocaPreviewIconeModo("modo_sem_forma_sim_rotaciona_com_limite");
                }
                else {
                    trocaPreviewIconeModo("modo_sem_forma_nao_rotaciona_com_limite");
                }
            }
        }
    }//GEN-LAST:event_radioBordaTelaSimActionPerformed

    private void radioRotacionarEstampasSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRotacionarEstampasSimActionPerformed
        if (radioRotacionarEstampasSim.isSelected()) {
            if (radioTelaFormaSim.isSelected()) {
                trocaPreviewIconeModo("modo_com_forma_sim_rotaciona");
            }
            else {
                if (radioBordaTelaSim.isSelected()) {
                    trocaPreviewIconeModo("modo_sem_forma_sim_rotaciona_com_limite");
                }
                else {
                    trocaPreviewIconeModo("modo_sem_forma_sim_rotaciona_sem_limite");
                }
            }
        }
    }//GEN-LAST:event_radioRotacionarEstampasSimActionPerformed

    private void radioRotacionarEstampasNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRotacionarEstampasNaoActionPerformed
        if (radioRotacionarEstampasNao.isSelected()) {
            if (radioTelaFormaSim.isSelected()) {
                trocaPreviewIconeModo("modo_com_forma_nao_rotaciona");
            }
            else {
                if (radioBordaTelaSim.isSelected()) {
                    trocaPreviewIconeModo("modo_sem_forma_nao_rotaciona_com_limite");
                }
                else {
                    trocaPreviewIconeModo("modo_sem_forma_nao_rotaciona_sem_limite");
                }
            }
        }
    }//GEN-LAST:event_radioRotacionarEstampasNaoActionPerformed

    private void estampaSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estampaSelecionarActionPerformed
        atualizarEstampas();
        frameEstampaEscolher.setLocation(dim.width/2-frameEstampaEscolher.getSize().width/2, dim.height/2-frameEstampaEscolher.getSize().height/2);
        frameEstampaEscolher.setVisible(true);
    }//GEN-LAST:event_estampaSelecionarActionPerformed

    private void estampaAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estampaAdicionarActionPerformed
        int retorno = fileEstampaAdicionar.showOpenDialog(this);
        if (retorno == javax.swing.JFileChooser.APPROVE_OPTION){
            File arquivo = fileEstampaAdicionar.getSelectedFile();
            canvasframeEstampa.setURI(arquivo.toURI().toString());
            File copia;
            try {
                copia = new File("./img/estampas/estampa" + numeroEstampa() + ".svg").getCanonicalFile();
                Files.copy(arquivo.toPath(),copia.toPath(), REPLACE_EXISTING);
            } catch (IOException ex) {
                Logger.getLogger(InterfaceUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_estampaAdicionarActionPerformed

    private void itemTexturaAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTexturaAdicionarActionPerformed
        int retorno = filePreenchimentoAdicionar.showOpenDialog(this);
        if (retorno == javax.swing.JFileChooser.APPROVE_OPTION){
            File arquivo = filePreenchimentoAdicionar.getSelectedFile();
            File copia;
            try {
                copia = new File("./img/texturas/textura" + numeroTextura() + ".svg").getCanonicalFile();
                Files.copy(arquivo.toPath(),copia.toPath(), REPLACE_EXISTING);
            } catch (IOException ex) {
                Logger.getLogger(InterfaceUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_itemTexturaAdicionarActionPerformed

    private void comboboxEstampasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxEstampasActionPerformed
        trocaIconeEstampa(canvasframeEstampa, (String) comboboxEstampas.getSelectedItem());
    }//GEN-LAST:event_comboboxEstampasActionPerformed

    private void itemTexturaSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTexturaSelecionarActionPerformed
        atualizarTexturas();
        frameTexturasEscolher.setLocation(dim.width/2-frameTexturasEscolher.getSize().width/2, dim.height/2-frameTexturasEscolher.getSize().height/2);
        frameTexturasEscolher.setVisible(true);
    }//GEN-LAST:event_itemTexturaSelecionarActionPerformed

    private void itemCoresSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCoresSelecionarActionPerformed
        frameCoresEscolher.setLocation(dim.width/2-frameCoresEscolher.getSize().width/2, dim.height/2-frameCoresEscolher.getSize().height/2);
        frameCoresEscolher.setVisible(true);
    }//GEN-LAST:event_itemCoresSelecionarActionPerformed

    private void comboboxTexturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxTexturasActionPerformed
        trocaIconeTextura(canvasframeTextura, (String) comboboxTexturas.getSelectedItem());
    }//GEN-LAST:event_comboboxTexturasActionPerformed

    private void botaoEstampaSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEstampaSelecionarActionPerformed
        estampa = (String) comboboxEstampas.getSelectedItem();
        trocaIconeEstampa(canvasPreviewEstampa, estampa);
    }//GEN-LAST:event_botaoEstampaSelecionarActionPerformed

    private void botaoEstampaSelecionarFundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEstampaSelecionarFundoActionPerformed
        forma_fundo = (String) comboboxEstampas.getSelectedItem();
        if (radioTelaFormaSim.isSelected())
            trocaIconeEstampa(canvasPreviewFormaFundo, forma_fundo);
    }//GEN-LAST:event_botaoEstampaSelecionarFundoActionPerformed

    private void botaoTexturaSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTexturaSelecionarActionPerformed
        textura = (String) comboboxTexturas.getSelectedItem();
        if (radioTipoPreenchimentoTexturas.isSelected())
            trocaIconeTextura(canvasPreviewPreenchimento, textura);
    }//GEN-LAST:event_botaoTexturaSelecionarActionPerformed

    private void botaoTexturaExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTexturaExcluirActionPerformed
        String nome = (String) comboboxTexturas.getSelectedItem();
        if (nome.equals("textura1.svg") || nome.equals("textura2.svg")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Não pode deletar este arquivo. Foi feito com muito carinho. :(",
                    "Erro",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        else{
            if (nome.equals(textura)){
                textura = "textura1.svg";
                if (radioTipoPreenchimentoTexturas.isSelected())
                    trocaIconeTextura(canvasPreviewPreenchimento, textura);
            }
            File arquivo = new File("./img/texturas/" + nome);
            arquivo.delete();
            atualizarTexturas();
            
        }
    }//GEN-LAST:event_botaoTexturaExcluirActionPerformed

    private void botaoEstampaExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEstampaExcluirActionPerformed
        String nome = (String) comboboxEstampas.getSelectedItem();
        if (nome.equals("estampa1.svg") || nome.equals("estampa2.svg") || nome.equals("estampa3.svg")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Não pode deletar este arquivo. Foi feito com muito carinho. :(",
                    "Erro",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        else{
            if (nome.equals(estampa)){
                estampa = "estampa1.svg";
                trocaIconeEstampa(canvasPreviewEstampa, estampa);
            }
            
            if (nome.equals(forma_fundo)){
                forma_fundo = "estampa1.svg";
                if (radioTelaFormaSim.isSelected())
                    trocaIconeEstampa(canvasPreviewFormaFundo, forma_fundo);
            }
            
            File arquivo = new File("./img/estampas/" + nome);
            arquivo.delete();
            atualizarEstampas();
        }
    }//GEN-LAST:event_botaoEstampaExcluirActionPerformed

    private void botaoFrameCoresFundoSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFrameCoresFundoSelecionarActionPerformed
        Color nova_cor = javax.swing.JColorChooser.showDialog(this, "Escolha a cor do fundo", cor_fundo_selecionada);
        if (nova_cor != null) {
            cor_fundo_selecionada = nova_cor;
            atualizaCoresPreview(previewCorFundo, cor_fundo_selecionada);
            atualizaCoresFrame(panelFrameCoresFundo, cor_fundo_selecionada);
        }
    }//GEN-LAST:event_botaoFrameCoresFundoSelecionarActionPerformed

    private void botaoIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIniciarActionPerformed
        Shape shape_tela = null;

        BridgeContext contexto = canvasPreviewEstampa.getUpdateManager().getBridgeContext();
        SVGDocument documento = canvasPreviewEstampa.getSVGDocument();
        contexto.setDynamicState(BridgeContext.DYNAMIC); 
        GVTBuilder gvt = new GVTBuilder(); 
        GraphicsNode nodo = gvt.build(contexto, documento); 
        GVTTreeWalker arvore = new GVTTreeWalker(nodo); 
        ArrayList<Shape> array_formas = new ArrayList<>();
        arvore.nextGraphicsNode(); // passa a GeneralPath
        while ( (nodo = arvore.nextGraphicsNode()) != null) { 
            array_formas.add(nodo.getOutline());
            System.out.println("ESTAMPA: " + nodo.getOutline());
        } 
        
        if (array_formas.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this,
                    "O arquivo SVG não possui forma(s). Não poderá ser utilizada. :(",
                    "Erro",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        else{
            System.out.println("TOTAL DE FORMAS DE ESTAMPA: " + array_formas.size());
            try{
                if (radioTelaFormaSim.isSelected()) {
                    // forma da tela
                    contexto = canvasPreviewFormaFundo.getUpdateManager().getBridgeContext();
                    documento = canvasPreviewFormaFundo.getSVGDocument();
                    contexto.setDynamicState(BridgeContext.DYNAMIC); 
                    gvt = new GVTBuilder(); 
                    nodo = gvt.build(contexto, documento); 
                    arvore = new GVTTreeWalker(nodo);
                    arvore.nextGraphicsNode();
                    nodo = arvore.nextGraphicsNode();
                    shape_tela = nodo.getOutline();
                    System.out.println("TELA: " + shape_tela);
                }

                // cores ou textura
                ArrayList<Preenchimento> preenchimentos = new ArrayList<>();

                if (radioTipoPreenchimentoTexturas.isSelected()) {
                    preenchimentos.add(new Preenchimento(criarImagem(canvasPreviewPreenchimento)));
                }
                else { //cores
                    Color aux;

                    for (int i = 0 ; i < quantidadeColunas ; i++) {
                        for (int j = 0 ; j < quantidadeLinhas ; j++) {
                            aux = (Color) tabelaVerCores.getModel().getValueAt(j, i);
                            if (aux.getAlpha() != 0) {
                                preenchimentos.add(new Preenchimento(aux));
                            }
                        }
                    }

                    if (preenchimentos.isEmpty()) {
                        preenchimentos.add(new Preenchimento(Color.BLACK));
                    }
                    System.out.println("TOTAL DE CORES: " + preenchimentos.size());
                }

                Tela.tela = new Tela(radioBordaTelaSim.isSelected(), radioRotacionarEstampasSim.isSelected(), radioTelaFormaSim.isSelected(), radioTipoPreenchimentoTexturas.isSelected());
                Tela.tela.preencherArea(array_formas, shape_tela, preenchimentos, cor_fundo_selecionada, (double) spinnerValorC.getValue(), (int) spinnerQuantidadeFormas.getValue(), (int) spinnerIteracoes.getValue());
                
            } catch (java.lang.NullPointerException ex){
                javax.swing.JOptionPane.showMessageDialog(this,
                        "O arquivo SVG não possui forma(s). Não poderá ser utilizada. :(",
                        "Erro",javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_botaoIniciarActionPerformed

    private void botaoVerCoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVerCoresActionPerformed
        frameVerCores.setLocation(dim.width/2-frameVerCores.getSize().width/2, dim.height/2-frameVerCores.getSize().height/2);
        frameVerCores.setVisible(true);
    }//GEN-LAST:event_botaoVerCoresActionPerformed

    private void botaoVerCoresEscolherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVerCoresEscolherActionPerformed
        frameVerCores.setLocation(dim.width/2-frameVerCores.getSize().width/2, dim.height/2-frameVerCores.getSize().height/2);
        frameVerCores.setVisible(true);
    }//GEN-LAST:event_botaoVerCoresEscolherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the default OS look and feel */
        
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        }
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(InterfaceUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InterfaceUsuario().setVisible(true);
        });
    }
    
    public void trocaPreviewIconeModo(String arquivo) {
        try{
            File g = new File("./img/icones/" + arquivo + ".svg").getCanonicalFile();
            canvasPreviewModo.setURI(g.toURI().toString());
        }
        catch(java.io.IOException e){}
    }
    
    public void trocaIconeTextura(org.apache.batik.swing.JSVGCanvas canvas, String arquivo) {
        try{
            File g = new File("./img/texturas/" + arquivo).getCanonicalFile();
            canvas.setURI(g.toURI().toString());
        }
        catch(java.io.IOException e){}
    }
    
    public void trocaIconeEstampa(org.apache.batik.swing.JSVGCanvas canvas, String arquivo) {
        try{
            File g = new File("./img/estampas/" + arquivo).getCanonicalFile();
            canvas.setURI(g.toURI().toString());
        }
        catch(java.io.IOException e){}
    }
    
    public void deixaVazio(org.apache.batik.swing.JSVGCanvas canvas) {
        try{
            File g = new File("./img/vazio.svg").getCanonicalFile();
            canvas.setURI(g.toURI().toString());
        }
        catch(java.io.IOException e){}
    }
    
    private int numeroEstampa() {
        try {
            int v = 1;
            File salva = new File("./img/estampas/estampa" + v + ".svg").getCanonicalFile();
            while (salva.exists()){
                v++;
                salva = new File("./img/estampas/estampa" + v + ".svg").getCanonicalFile();
            }
            return v;
        } catch (IOException ex) {
            Logger.getLogger(InterfaceUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return 0;
    }
    
    private int numeroTextura(){
        try{
            int v = 1;
            File salva = new File("./img/texturas/textura" + v + ".svg").getCanonicalFile();
            while (salva.exists()){
                v++;
                salva = new File("./img/texturas/textura" + v + ".svg").getCanonicalFile();
            }
            return v;
        } catch (IOException ex) {
            Logger.getLogger(InterfaceUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return 0;
    }
    
    private void atualizarEstampas() {
        File folder = new File("./img/estampas");

        File[] lista_arquivos = folder.listFiles();
        ArrayList<String> nomes_arquivos = new ArrayList<>();
        for (File x : lista_arquivos) {
            if (x.isFile()) {
                nomes_arquivos.add(x.getName());
            }
        }
        String [] valores = new String[nomes_arquivos.size()];
        for (int i = 0 ; i < nomes_arquivos.size() ; i++)
            valores[i] = nomes_arquivos.get(i);
        
        comboboxEstampas.setModel(new javax.swing.DefaultComboBoxModel<>(valores));
        trocaIconeEstampa(canvasframeEstampa, (String) comboboxEstampas.getSelectedItem());
    }
    
    private void atualizarTexturas() {
        File folder = new File("./img/texturas");

        File[] lista_arquivos = folder.listFiles();
        ArrayList<String> nomes_arquivos = new ArrayList<>();
        for (File x : lista_arquivos) {
            if (x.isFile()) {
                nomes_arquivos.add(x.getName());
            }
        }
        
        String [] valores = new String[nomes_arquivos.size()];
        for (int i = 0 ; i < nomes_arquivos.size() ; i++)
            valores[i] = nomes_arquivos.get(i);
        
        comboboxTexturas.setModel(new javax.swing.DefaultComboBoxModel<>(valores));
        trocaIconeTextura(canvasframeTextura, (String) comboboxTexturas.getSelectedItem());
    }
    
    private void atualizaCoresPreview(javax.swing.JPanel preview, Color cor) {
        if (cor != null) {
            preview.setBackground(cor);
            preview.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK));
        }
        else {
            preview.setBackground(new java.awt.Color(240, 240, 240));
            preview.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        }
    }
    
    private void atualizaCoresFrame(javax.swing.JPanel preview, Color cor) {
        if (cor != null) {
            preview.setBackground(cor);
        }
        else {
            preview.setBackground(new java.awt.Color(240, 240, 240));
        }
    }
    
    private BufferedImage criarImagem(org.apache.batik.swing.JSVGCanvas canvas) {
        BufferedImage imagem = new BufferedImage(100, 100, BufferedImage.TYPE_INT_ARGB);
        Graphics2D cg = imagem.createGraphics();
        canvas.paintAll(cg);
        //cg.scale(5, 5);
        return imagem;
    }
    
    public class editorDeCor extends AbstractCellEditor implements
            TableCellEditor, ActionListener {
        Color corAtual;
        JButton botao;
        JColorChooser colorChooser;
        JDialog dialog;

        public editorDeCor() {
            botao = new JButton();
            botao.addActionListener(this);
            botao.setBorderPainted(false);
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            botao.setBackground(corAtual);
            Color nova_cor = javax.swing.JColorChooser.showDialog(null, "Escolha a cor do fundo", corAtual);
            if (nova_cor != null) {
                corAtual = nova_cor;
            }
            fireEditingStopped();
        }

        @Override
        public Object getCellEditorValue() {
            return corAtual;
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value,
                boolean isSelected, int row, int column) {
            corAtual = (Color)value;
            return botao;
        }
    }


    public class RenderizadorDeCor extends JLabel implements TableCellRenderer {
        Border bordaNaoSelecionada = null;
        Border bordaSelecionada = null;
        boolean isComBorda = true;

        public RenderizadorDeCor(boolean isBordered) {
            this.isComBorda = isBordered;
            setOpaque(true);
        }

        @Override
        public Component getTableCellRendererComponent( JTable table, Object color,
                boolean isSelected, boolean hasFocus, int row, int column) {
            Color newColor = (Color)color;
            setBackground(newColor);
            if (isComBorda) {
                if (isSelected) {
                    if (bordaSelecionada == null) {
                        bordaSelecionada = BorderFactory.createMatteBorder(2,5,2,5,
                                table.getSelectionBackground());
                    }
                    setBorder(bordaSelecionada);
                } else {
                    if (bordaNaoSelecionada == null) {
                        bordaNaoSelecionada = BorderFactory.createMatteBorder(2,5,2,5,
                                table.getBackground());
                    }
                    setBorder(bordaNaoSelecionada);
                }
            }

        String texto;
        
        if (newColor.getAlpha() == 0) {
            texto = "Tecnicamente vazio";
        }
        else{
           texto = "Cores RGBA: " + newColor.getRed() + ", " + 
                newColor.getGreen() + ", " + newColor.getBlue() + ", " + 
                newColor.getAlpha();
        }
        
        setToolTipText(texto);
            return this;
        }
    }
    
    class modeloTabelaCores extends AbstractTableModel {
        Color vazio = new Color(0,0,0,0);
        private String[] columnNames = {"", "", "", "", ""};
        private Object[][] data = {
            {Color.BLACK, vazio, vazio, vazio, vazio},
            {vazio, vazio, vazio, vazio, vazio},
            {vazio, vazio, vazio, vazio, vazio},
            {vazio, vazio, vazio, vazio, vazio},
            {vazio, vazio, vazio, vazio, vazio},
            {vazio, vazio, vazio, vazio, vazio},
            {vazio, vazio, vazio, vazio, vazio},
            {vazio, vazio, vazio, vazio, vazio},
            {vazio, vazio, vazio, vazio, vazio},
            {vazio, vazio, vazio, vazio, vazio},
            };
        
        @Override
        public int getColumnCount() {
            return columnNames.length;
        }
        
        @Override
        public int getRowCount() {
            return data.length;
        }

        @Override
        public String getColumnName(int col) {
            return columnNames[col];
        }

        @Override
        public Object getValueAt(int row, int col) {
            return data[row][col];
        }

        @Override
        public Class getColumnClass(int c) {
            return getValueAt(0, c).getClass();
        }

        @Override
        public boolean isCellEditable(int row, int col) {
            return col >= 0;
        }

        @Override
        public void setValueAt(Object value, int row, int col) {
            data[row][col] = value;
            fireTableCellUpdated(row, col);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botaoEstampaExcluir;
    private javax.swing.JButton botaoEstampaSelecionar;
    private javax.swing.JButton botaoEstampaSelecionarFundo;
    private javax.swing.JButton botaoFrameCoresFundoSelecionar;
    private javax.swing.JButton botaoIniciar;
    private javax.swing.JButton botaoTexturaExcluir;
    private javax.swing.JButton botaoTexturaSelecionar;
    private javax.swing.JButton botaoVerCores;
    private javax.swing.JButton botaoVerCoresEscolher;
    private javax.swing.ButtonGroup buttonGroupBordaTela;
    private javax.swing.ButtonGroup buttonGroupRotacionarEstampas;
    private javax.swing.ButtonGroup buttonGroupTelaForma;
    private javax.swing.ButtonGroup buttonGroupTipoPreenchimento;
    private org.apache.batik.swing.JSVGCanvas canvasPreviewEstampa;
    private org.apache.batik.swing.JSVGCanvas canvasPreviewFormaFundo;
    private org.apache.batik.swing.JSVGCanvas canvasPreviewModo;
    private org.apache.batik.swing.JSVGCanvas canvasPreviewPreenchimento;
    private org.apache.batik.swing.JSVGCanvas canvasframeEstampa;
    private org.apache.batik.swing.JSVGCanvas canvasframeTextura;
    private javax.swing.JComboBox<String> comboboxEstampas;
    private javax.swing.JComboBox<String> comboboxTexturas;
    private javax.swing.JMenuItem estampaAdicionar;
    private javax.swing.JMenuItem estampaSelecionar;
    private javax.swing.JFileChooser fileEstampaAdicionar;
    private javax.swing.JFileChooser filePreenchimentoAdicionar;
    private javax.swing.JFrame frameCoresEscolher;
    private javax.swing.JFrame frameEstampaEscolher;
    private javax.swing.JFrame frameTexturasEscolher;
    private javax.swing.JFrame frameVerCores;
    private javax.swing.JMenuItem itemCoresSelecionar;
    private javax.swing.JMenuItem itemManual;
    private javax.swing.JMenuItem itemSobre;
    private javax.swing.JMenuItem itemTexturaAdicionar;
    private javax.swing.JMenuItem itemTexturaSelecionar;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuCores;
    private javax.swing.JMenu menuEstampas;
    private javax.swing.JMenu menuPreenchimento;
    private javax.swing.JMenu menuTextura;
    private javax.swing.JPanel panelCorpo;
    private javax.swing.JPanel panelFrameCoresFundo;
    private javax.swing.JSeparator panelSeparador;
    private javax.swing.JPanel previewCorFundo;
    private javax.swing.JRadioButton radioBordaTelaNao;
    private javax.swing.JRadioButton radioBordaTelaSim;
    private javax.swing.JRadioButton radioRotacionarEstampasNao;
    private javax.swing.JRadioButton radioRotacionarEstampasSim;
    private javax.swing.JRadioButton radioTelaFormaNao;
    private javax.swing.JRadioButton radioTelaFormaSim;
    private javax.swing.JRadioButton radioTipoPreenchimentoCores;
    private javax.swing.JRadioButton radioTipoPreenchimentoTexturas;
    private javax.swing.JSpinner spinnerIteracoes;
    private javax.swing.JSpinner spinnerQuantidadeFormas;
    private javax.swing.JSpinner spinnerValorC;
    private javax.swing.JTable tabelaVerCores;
    private javax.swing.JLabel textoBordaTela;
    private javax.swing.JLabel textoFrameCoresCorpo;
    private javax.swing.JLabel textoFrameCoresEstampas;
    private javax.swing.JLabel textoFrameCoresFundo;
    private javax.swing.JLabel textoFrameEstampaCorpo;
    private javax.swing.JLabel textoFrameEstampaPreview;
    private javax.swing.JLabel textoFrameTexturaCorpo;
    private javax.swing.JLabel textoFrameTexturaPreview;
    private javax.swing.JLabel textoIteracoes;
    private javax.swing.JLabel textoPreview;
    private javax.swing.JLabel textoPreviewCorFundo;
    private javax.swing.JLabel textoPreviewEstampa;
    private javax.swing.JLabel textoPreviewFormaFundo;
    private javax.swing.JLabel textoPreviewModo;
    private javax.swing.JLabel textoPreviewPreenchimento;
    private javax.swing.JLabel textoPreviewPreenchimentoCores;
    private javax.swing.JLabel textoPreviewPreenchimentoTextura;
    private javax.swing.JLabel textoQuantidadeFormas;
    private javax.swing.JLabel textoRotacionarEstampas;
    private javax.swing.JLabel textoTelaForma;
    private javax.swing.JLabel textoTipoPreenchimento;
    private javax.swing.JLabel textoTitulo;
    private javax.swing.JLabel textoValorC;
    // End of variables declaration//GEN-END:variables
}
