/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mosaicofractal.gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Giordanna
 */
public class InterfaceUsuario extends javax.swing.JFrame {
    
    private Color cor_fundo_selecionada = Color.WHITE;
    private int qtd_cores = 1;
    private Color [] cores_estampas = {Color.BLACK, null, null, null};
    private int textura = 1;
    private int estampa = 1;
    private int forma_fundo = 1;
    
    /**
     * Creates new form InterfaceUsuario
     */
    public InterfaceUsuario() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(dim.width/2-getSize().width/2, dim.height/2-getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupBordaTela = new javax.swing.ButtonGroup();
        buttonGroupRotacionarEstampas = new javax.swing.ButtonGroup();
        buttonGroupTelaForma = new javax.swing.ButtonGroup();
        buttonGroupTipoPreenchimento = new javax.swing.ButtonGroup();
        fileEstampaAdicionar = new javax.swing.JFileChooser();
        filePreenchimentoAdicionar = new javax.swing.JFileChooser();
        frameEstampaEscolher = new javax.swing.JFrame();
        comboboxEstampas = new javax.swing.JComboBox<>();
        textoFrameEstampaCorpo = new javax.swing.JLabel();
        canvasframeEstampa = new org.apache.batik.swing.JSVGCanvas();
        botaoEstampaSelecionar = new javax.swing.JButton();
        botaoEstampaExcluir = new javax.swing.JButton();
        textoFrameEstampaPreview = new javax.swing.JLabel();
        frameTexturasEscolher = new javax.swing.JFrame();
        comboboxTexturas = new javax.swing.JComboBox<>();
        textoFrameTexturaCorpo = new javax.swing.JLabel();
        canvasframeTextura = new org.apache.batik.swing.JSVGCanvas();
        botaoTexturaSelecionar = new javax.swing.JButton();
        botaoTexturaExcluir = new javax.swing.JButton();
        textoFrameTexturaPreview = new javax.swing.JLabel();
        frameCoresEscolher = new javax.swing.JFrame();
        textoFrameCoresCorpo = new javax.swing.JLabel();
        textoFrameCoresEstampas = new javax.swing.JLabel();
        textoFrameCoresFundo = new javax.swing.JLabel();
        panelFrameCoresEstampa1 = new javax.swing.JPanel();
        panelFrameCoresEstampa2 = new javax.swing.JPanel();
        panelFrameCoresEstampa3 = new javax.swing.JPanel();
        panelFrameCoresEstampa4 = new javax.swing.JPanel();
        panelFrameCoresFundo = new javax.swing.JPanel();
        botaoFrameCoresEstampaSelecionar = new javax.swing.JButton();
        botaoFrameCoresEstampaApagar = new javax.swing.JButton();
        botaoFrameCoresFundoSelecionar = new javax.swing.JButton();
        escolherCor = new javax.swing.JColorChooser();
        panelCorpo = new javax.swing.JPanel();
        textoValorC = new javax.swing.JLabel();
        spinnerValorC = new javax.swing.JSpinner();
        textoPreview = new javax.swing.JLabel();
        botaoIniciar = new javax.swing.JButton();
        textoBordaTela = new javax.swing.JLabel();
        radioBordaTelaSim = new javax.swing.JRadioButton();
        radioBordaTelaNao = new javax.swing.JRadioButton();
        textoRotacionarEstampas = new javax.swing.JLabel();
        radioRotacionarEstampasSim = new javax.swing.JRadioButton();
        radioRotacionarEstampasNao = new javax.swing.JRadioButton();
        textoTelaForma = new javax.swing.JLabel();
        radioTelaFormaSim = new javax.swing.JRadioButton();
        radioTelaFormaNao = new javax.swing.JRadioButton();
        textoTipoPreenchimento = new javax.swing.JLabel();
        radioTipoPreenchimentoCores = new javax.swing.JRadioButton();
        radioTipoPreenchimentoTexturas = new javax.swing.JRadioButton();
        panelSeparador = new javax.swing.JSeparator();
        canvasPreviewModo = new org.apache.batik.swing.JSVGCanvas();
        canvasPreviewPreenchimento = new org.apache.batik.swing.JSVGCanvas();
        textoPreviewModo = new javax.swing.JLabel();
        textoPreviewEstampa = new javax.swing.JLabel();
        textoPreviewPreenchimento = new javax.swing.JLabel();
        textoPreviewPreenchimentoCores = new javax.swing.JLabel();
        textoPreviewPreenchimentoTextura = new javax.swing.JLabel();
        canvasPreviewEstampa = new org.apache.batik.swing.JSVGCanvas();
        previewCorPaleta1 = new javax.swing.JPanel();
        previewCorPaleta2 = new javax.swing.JPanel();
        previewCorPaleta3 = new javax.swing.JPanel();
        previewCorPaleta4 = new javax.swing.JPanel();
        textoPreviewCorFundo = new javax.swing.JLabel();
        previewCorFundo = new javax.swing.JPanel();
        textoPreviewFormaFundo = new javax.swing.JLabel();
        canvasPreviewFormaFundo = new org.apache.batik.swing.JSVGCanvas();
        textoTitulo = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuEstampas = new javax.swing.JMenu();
        estampaAdicionar = new javax.swing.JMenuItem();
        estampaSelecionar = new javax.swing.JMenuItem();
        menuPreenchimento = new javax.swing.JMenu();
        menuCores = new javax.swing.JMenu();
        itemCoresSelecionar = new javax.swing.JMenuItem();
        menuTextura = new javax.swing.JMenu();
        itemTexturaAdicionar = new javax.swing.JMenuItem();
        itemTexturaSelecionar = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        itemManual = new javax.swing.JMenuItem();
        itemSobre = new javax.swing.JMenuItem();

        fileEstampaAdicionar.setFileFilter(new FileNameExtensionFilter("SVG", "svg"));

        filePreenchimentoAdicionar.setFileFilter(new FileNameExtensionFilter("SVG", "svg"));

        frameEstampaEscolher.setTitle("Escolher Estampas");

        comboboxEstampas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        textoFrameEstampaCorpo.setText("Escolha uma das estampas disponíveis e selecione a sua opção desejada:");

        canvasframeEstampa.setEnableImageZoomInteractor(false);
        canvasframeEstampa.setEnablePanInteractor(false);
        canvasframeEstampa.setEnableResetTransformInteractor(false);
        canvasframeEstampa.setEnableRotateInteractor(false);
        canvasframeEstampa.setEnableZoomInteractor(false);
        canvasframeEstampa.setPreferredSize(new java.awt.Dimension(150, 150));

        botaoEstampaSelecionar.setText("Selecionar");

        botaoEstampaExcluir.setText("Excluir");

        textoFrameEstampaPreview.setText("Preview:");

        javax.swing.GroupLayout frameEstampaEscolherLayout = new javax.swing.GroupLayout(frameEstampaEscolher.getContentPane());
        frameEstampaEscolher.getContentPane().setLayout(frameEstampaEscolherLayout);
        frameEstampaEscolherLayout.setHorizontalGroup(
            frameEstampaEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameEstampaEscolherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameEstampaEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textoFrameEstampaCorpo)
                    .addGroup(frameEstampaEscolherLayout.createSequentialGroup()
                        .addGroup(frameEstampaEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frameEstampaEscolherLayout.createSequentialGroup()
                                .addComponent(botaoEstampaSelecionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoEstampaExcluir))
                            .addGroup(frameEstampaEscolherLayout.createSequentialGroup()
                                .addComponent(comboboxEstampas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textoFrameEstampaPreview)))
                        .addGap(18, 18, 18)
                        .addComponent(canvasframeEstampa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frameEstampaEscolherLayout.setVerticalGroup(
            frameEstampaEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameEstampaEscolherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoFrameEstampaCorpo)
                .addGap(18, 18, 18)
                .addGroup(frameEstampaEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(frameEstampaEscolherLayout.createSequentialGroup()
                        .addGroup(frameEstampaEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboboxEstampas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoFrameEstampaPreview))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(frameEstampaEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoEstampaSelecionar)
                            .addComponent(botaoEstampaExcluir)))
                    .addComponent(canvasframeEstampa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        frameTexturasEscolher.setTitle("Escolher Texturas");

        comboboxTexturas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        textoFrameTexturaCorpo.setText("Escolha uma das texturas disponíveis e selecione a sua opção desejada:");

        canvasframeTextura.setEnableImageZoomInteractor(false);
        canvasframeTextura.setEnablePanInteractor(false);
        canvasframeTextura.setEnableResetTransformInteractor(false);
        canvasframeTextura.setEnableRotateInteractor(false);
        canvasframeTextura.setEnableZoomInteractor(false);
        canvasframeTextura.setPreferredSize(new java.awt.Dimension(150, 150));

        botaoTexturaSelecionar.setText("Selecionar");

        botaoTexturaExcluir.setText("Excluir");

        textoFrameTexturaPreview.setText("Preview:");

        javax.swing.GroupLayout frameTexturasEscolherLayout = new javax.swing.GroupLayout(frameTexturasEscolher.getContentPane());
        frameTexturasEscolher.getContentPane().setLayout(frameTexturasEscolherLayout);
        frameTexturasEscolherLayout.setHorizontalGroup(
            frameTexturasEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameTexturasEscolherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameTexturasEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(frameTexturasEscolherLayout.createSequentialGroup()
                        .addComponent(textoFrameTexturaCorpo)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(frameTexturasEscolherLayout.createSequentialGroup()
                        .addGroup(frameTexturasEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frameTexturasEscolherLayout.createSequentialGroup()
                                .addComponent(botaoTexturaSelecionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoTexturaExcluir))
                            .addGroup(frameTexturasEscolherLayout.createSequentialGroup()
                                .addComponent(comboboxTexturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textoFrameTexturaPreview)))
                        .addGap(18, 18, 18)
                        .addComponent(canvasframeTextura, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        frameTexturasEscolherLayout.setVerticalGroup(
            frameTexturasEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameTexturasEscolherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoFrameTexturaCorpo)
                .addGap(18, 18, 18)
                .addGroup(frameTexturasEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(frameTexturasEscolherLayout.createSequentialGroup()
                        .addGroup(frameTexturasEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboboxTexturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoFrameTexturaPreview))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(frameTexturasEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoTexturaSelecionar)
                            .addComponent(botaoTexturaExcluir)))
                    .addComponent(canvasframeTextura, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        frameCoresEscolher.setTitle("Escolher Cores");

        textoFrameCoresCorpo.setText("Escolha as cores desejadas:");

        textoFrameCoresEstampas.setText("Estampas:");

        textoFrameCoresFundo.setText("Para o fundo:");

        panelFrameCoresEstampa1.setBackground(new java.awt.Color(0, 0, 0));
        panelFrameCoresEstampa1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2)));

        javax.swing.GroupLayout panelFrameCoresEstampa1Layout = new javax.swing.GroupLayout(panelFrameCoresEstampa1);
        panelFrameCoresEstampa1.setLayout(panelFrameCoresEstampa1Layout);
        panelFrameCoresEstampa1Layout.setHorizontalGroup(
            panelFrameCoresEstampa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelFrameCoresEstampa1Layout.setVerticalGroup(
            panelFrameCoresEstampa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        panelFrameCoresEstampa2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelFrameCoresEstampa2Layout = new javax.swing.GroupLayout(panelFrameCoresEstampa2);
        panelFrameCoresEstampa2.setLayout(panelFrameCoresEstampa2Layout);
        panelFrameCoresEstampa2Layout.setHorizontalGroup(
            panelFrameCoresEstampa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelFrameCoresEstampa2Layout.setVerticalGroup(
            panelFrameCoresEstampa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        panelFrameCoresEstampa3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelFrameCoresEstampa3Layout = new javax.swing.GroupLayout(panelFrameCoresEstampa3);
        panelFrameCoresEstampa3.setLayout(panelFrameCoresEstampa3Layout);
        panelFrameCoresEstampa3Layout.setHorizontalGroup(
            panelFrameCoresEstampa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelFrameCoresEstampa3Layout.setVerticalGroup(
            panelFrameCoresEstampa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        panelFrameCoresEstampa4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelFrameCoresEstampa4Layout = new javax.swing.GroupLayout(panelFrameCoresEstampa4);
        panelFrameCoresEstampa4.setLayout(panelFrameCoresEstampa4Layout);
        panelFrameCoresEstampa4Layout.setHorizontalGroup(
            panelFrameCoresEstampa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelFrameCoresEstampa4Layout.setVerticalGroup(
            panelFrameCoresEstampa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        panelFrameCoresFundo.setBackground(new java.awt.Color(255, 255, 255));
        panelFrameCoresFundo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelFrameCoresFundoLayout = new javax.swing.GroupLayout(panelFrameCoresFundo);
        panelFrameCoresFundo.setLayout(panelFrameCoresFundoLayout);
        panelFrameCoresFundoLayout.setHorizontalGroup(
            panelFrameCoresFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelFrameCoresFundoLayout.setVerticalGroup(
            panelFrameCoresFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        botaoFrameCoresEstampaSelecionar.setText("Selecionar");

        botaoFrameCoresEstampaApagar.setText("Apagar");

        botaoFrameCoresFundoSelecionar.setText("Selecionar");

        javax.swing.GroupLayout frameCoresEscolherLayout = new javax.swing.GroupLayout(frameCoresEscolher.getContentPane());
        frameCoresEscolher.getContentPane().setLayout(frameCoresEscolherLayout);
        frameCoresEscolherLayout.setHorizontalGroup(
            frameCoresEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameCoresEscolherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameCoresEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoFrameCoresCorpo)
                    .addComponent(textoFrameCoresEstampas)
                    .addComponent(textoFrameCoresFundo)
                    .addGroup(frameCoresEscolherLayout.createSequentialGroup()
                        .addComponent(panelFrameCoresEstampa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelFrameCoresEstampa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelFrameCoresEstampa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelFrameCoresEstampa4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoFrameCoresEstampaSelecionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoFrameCoresEstampaApagar))
                    .addGroup(frameCoresEscolherLayout.createSequentialGroup()
                        .addComponent(panelFrameCoresFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoFrameCoresFundoSelecionar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frameCoresEscolherLayout.setVerticalGroup(
            frameCoresEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameCoresEscolherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoFrameCoresCorpo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoFrameCoresEstampas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameCoresEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameCoresEscolherLayout.createSequentialGroup()
                        .addGroup(frameCoresEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelFrameCoresEstampa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelFrameCoresEstampa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelFrameCoresEstampa4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(frameCoresEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botaoFrameCoresEstampaSelecionar)
                                .addComponent(botaoFrameCoresEstampaApagar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoFrameCoresFundo))
                    .addComponent(panelFrameCoresEstampa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameCoresEscolherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFrameCoresFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoFrameCoresFundoSelecionar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mosaico Fractal");
        setResizable(false);

        textoValorC.setText("Valor de c:");

        spinnerValorC.setModel(new javax.swing.SpinnerNumberModel(1.48d, 1.0d, 1.48d, 0.01d));

        textoPreview.setText("Preview:");

        botaoIniciar.setText("Iniciar");

        textoBordaTela.setText("Considerar as bordas da tela como limites do mosaico?");

        buttonGroupBordaTela.add(radioBordaTelaSim);
        radioBordaTelaSim.setSelected(true);
        radioBordaTelaSim.setText("Sim");
        radioBordaTelaSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBordaTelaSimActionPerformed(evt);
            }
        });

        buttonGroupBordaTela.add(radioBordaTelaNao);
        radioBordaTelaNao.setText("Não");
        radioBordaTelaNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBordaTelaNaoActionPerformed(evt);
            }
        });

        textoRotacionarEstampas.setText("Rotacionar as estampas aleatoriamente?");

        buttonGroupRotacionarEstampas.add(radioRotacionarEstampasSim);
        radioRotacionarEstampasSim.setText("Sim");
        radioRotacionarEstampasSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRotacionarEstampasSimActionPerformed(evt);
            }
        });

        buttonGroupRotacionarEstampas.add(radioRotacionarEstampasNao);
        radioRotacionarEstampasNao.setSelected(true);
        radioRotacionarEstampasNao.setText("Não");
        radioRotacionarEstampasNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRotacionarEstampasNaoActionPerformed(evt);
            }
        });

        textoTelaForma.setText("A tela terá uma forma específica?");

        buttonGroupTelaForma.add(radioTelaFormaSim);
        radioTelaFormaSim.setText("Sim");
        radioTelaFormaSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTelaFormaSimActionPerformed(evt);
            }
        });

        buttonGroupTelaForma.add(radioTelaFormaNao);
        radioTelaFormaNao.setSelected(true);
        radioTelaFormaNao.setText("Não");
        radioTelaFormaNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTelaFormaNaoActionPerformed(evt);
            }
        });

        textoTipoPreenchimento.setText("O que será usado como preenchimento?");

        buttonGroupTipoPreenchimento.add(radioTipoPreenchimentoCores);
        radioTipoPreenchimentoCores.setSelected(true);
        radioTipoPreenchimentoCores.setText("Cores");
        radioTipoPreenchimentoCores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTipoPreenchimentoCoresActionPerformed(evt);
            }
        });

        buttonGroupTipoPreenchimento.add(radioTipoPreenchimentoTexturas);
        radioTipoPreenchimentoTexturas.setText("Texturas");
        radioTipoPreenchimentoTexturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTipoPreenchimentoTexturasActionPerformed(evt);
            }
        });

        canvasPreviewModo.setBackground(new java.awt.Color(240, 240, 240));
        canvasPreviewModo.setEnableImageZoomInteractor(false);
        canvasPreviewModo.setEnablePanInteractor(false);
        canvasPreviewModo.setEnableResetTransformInteractor(false);
        canvasPreviewModo.setEnableRotateInteractor(false);
        canvasPreviewModo.setEnableZoomInteractor(false);
        canvasPreviewModo.setPreferredSize(new java.awt.Dimension(100, 100));

        try{
            File g = new File("src/mosaicofractal/gui/icones/modo_sem_forma_nao_rotaciona_com_limite.svg").getCanonicalFile();
            canvasPreviewModo.setURI(g.toURI().toString());
        }
        catch(java.io.IOException e){
        }

        canvasPreviewPreenchimento.setBackground(new java.awt.Color(240, 240, 240));
        canvasPreviewPreenchimento.setEnableImageZoomInteractor(false);
        canvasPreviewPreenchimento.setEnablePanInteractor(false);
        canvasPreviewPreenchimento.setEnableResetTransformInteractor(false);
        canvasPreviewPreenchimento.setEnableRotateInteractor(false);
        canvasPreviewPreenchimento.setEnableZoomInteractor(false);
        canvasPreviewPreenchimento.setPreferredSize(new java.awt.Dimension(100, 100));

        textoPreviewModo.setText("Modo:");

        textoPreviewEstampa.setText("Estampa:");

        textoPreviewPreenchimento.setText("Preenchimento:");

        textoPreviewPreenchimentoCores.setText("Cores? Sim. Sendo elas:");

        textoPreviewPreenchimentoTextura.setForeground(java.awt.SystemColor.textInactiveText);
        textoPreviewPreenchimentoTextura.setText("Textura? Não.");

        canvasPreviewEstampa.setBackground(new java.awt.Color(240, 240, 240));
        canvasPreviewEstampa.setEnableImageZoomInteractor(false);
        canvasPreviewEstampa.setEnablePanInteractor(false);
        canvasPreviewEstampa.setEnableResetTransformInteractor(false);
        canvasPreviewEstampa.setEnableRotateInteractor(false);
        canvasPreviewEstampa.setEnableZoomInteractor(false);
        canvasPreviewEstampa.setPreferredSize(new java.awt.Dimension(100, 100));

        try{
            File g = new File("src/mosaicofractal/arquivos/estampas/estampa1.svg").getCanonicalFile();
            canvasPreviewEstampa.setURI(g.toURI().toString());
        }
        catch(java.io.IOException e){
        }

        previewCorPaleta1.setBackground(new java.awt.Color(0, 0, 0));
        previewCorPaleta1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        previewCorPaleta1.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout previewCorPaleta1Layout = new javax.swing.GroupLayout(previewCorPaleta1);
        previewCorPaleta1.setLayout(previewCorPaleta1Layout);
        previewCorPaleta1Layout.setHorizontalGroup(
            previewCorPaleta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        previewCorPaleta1Layout.setVerticalGroup(
            previewCorPaleta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        previewCorPaleta2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        previewCorPaleta2.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout previewCorPaleta2Layout = new javax.swing.GroupLayout(previewCorPaleta2);
        previewCorPaleta2.setLayout(previewCorPaleta2Layout);
        previewCorPaleta2Layout.setHorizontalGroup(
            previewCorPaleta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        previewCorPaleta2Layout.setVerticalGroup(
            previewCorPaleta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        previewCorPaleta3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        previewCorPaleta3.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout previewCorPaleta3Layout = new javax.swing.GroupLayout(previewCorPaleta3);
        previewCorPaleta3.setLayout(previewCorPaleta3Layout);
        previewCorPaleta3Layout.setHorizontalGroup(
            previewCorPaleta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        previewCorPaleta3Layout.setVerticalGroup(
            previewCorPaleta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        previewCorPaleta4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        previewCorPaleta4.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout previewCorPaleta4Layout = new javax.swing.GroupLayout(previewCorPaleta4);
        previewCorPaleta4.setLayout(previewCorPaleta4Layout);
        previewCorPaleta4Layout.setHorizontalGroup(
            previewCorPaleta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        previewCorPaleta4Layout.setVerticalGroup(
            previewCorPaleta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        textoPreviewCorFundo.setText("Cor do Fundo:");

        previewCorFundo.setBackground(new java.awt.Color(255, 255, 255));
        previewCorFundo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        previewCorFundo.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout previewCorFundoLayout = new javax.swing.GroupLayout(previewCorFundo);
        previewCorFundo.setLayout(previewCorFundoLayout);
        previewCorFundoLayout.setHorizontalGroup(
            previewCorFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        previewCorFundoLayout.setVerticalGroup(
            previewCorFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        textoPreviewFormaFundo.setText("Fundo normal.");

        canvasPreviewFormaFundo.setBackground(new java.awt.Color(240, 240, 240));
        canvasPreviewFormaFundo.setEnableImageZoomInteractor(false);
        canvasPreviewFormaFundo.setEnablePanInteractor(false);
        canvasPreviewFormaFundo.setEnableResetTransformInteractor(false);
        canvasPreviewFormaFundo.setEnableRotateInteractor(false);
        canvasPreviewFormaFundo.setEnableZoomInteractor(false);
        canvasPreviewFormaFundo.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout panelCorpoLayout = new javax.swing.GroupLayout(panelCorpo);
        panelCorpo.setLayout(panelCorpoLayout);
        panelCorpoLayout.setHorizontalGroup(
            panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCorpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSeparador)
                    .addGroup(panelCorpoLayout.createSequentialGroup()
                        .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCorpoLayout.createSequentialGroup()
                                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoPreviewModo)
                                    .addComponent(canvasPreviewModo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(canvasPreviewEstampa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoPreviewEstampa))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoPreviewFormaFundo)
                                    .addComponent(canvasPreviewFormaFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoPreviewPreenchimento)
                                    .addGroup(panelCorpoLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelCorpoLayout.createSequentialGroup()
                                                .addComponent(previewCorPaleta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(previewCorPaleta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(previewCorPaleta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(previewCorPaleta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(textoPreviewPreenchimentoCores)
                                            .addComponent(textoPreviewPreenchimentoTextura)
                                            .addComponent(textoPreviewCorFundo)
                                            .addComponent(previewCorFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                .addComponent(canvasPreviewPreenchimento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCorpoLayout.createSequentialGroup()
                                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelCorpoLayout.createSequentialGroup()
                                        .addComponent(radioTelaFormaSim)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioTelaFormaNao))
                                    .addGroup(panelCorpoLayout.createSequentialGroup()
                                        .addComponent(radioRotacionarEstampasSim)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioRotacionarEstampasNao))
                                    .addComponent(textoBordaTela)
                                    .addGroup(panelCorpoLayout.createSequentialGroup()
                                        .addComponent(radioBordaTelaSim)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioBordaTelaNao))
                                    .addComponent(textoRotacionarEstampas)
                                    .addComponent(textoTelaForma)
                                    .addGroup(panelCorpoLayout.createSequentialGroup()
                                        .addComponent(textoValorC)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spinnerValorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(textoTipoPreenchimento)
                                    .addGroup(panelCorpoLayout.createSequentialGroup()
                                        .addComponent(radioTipoPreenchimentoCores)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioTipoPreenchimentoTexturas))
                                    .addComponent(textoPreview)
                                    .addComponent(botaoIniciar))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        panelCorpoLayout.setVerticalGroup(
            panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCorpoLayout.createSequentialGroup()
                .addComponent(textoBordaTela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBordaTelaSim)
                    .addComponent(radioBordaTelaNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoRotacionarEstampas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioRotacionarEstampasSim)
                    .addComponent(radioRotacionarEstampasNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoTelaForma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioTelaFormaSim)
                    .addComponent(radioTelaFormaNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoTipoPreenchimento, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioTipoPreenchimentoCores)
                    .addComponent(radioTipoPreenchimentoTexturas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoValorC)
                    .addComponent(spinnerValorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoIniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoPreview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPreviewModo)
                    .addComponent(textoPreviewEstampa)
                    .addComponent(textoPreviewPreenchimento)
                    .addComponent(textoPreviewFormaFundo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canvasPreviewModo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canvasPreviewPreenchimento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canvasPreviewEstampa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCorpoLayout.createSequentialGroup()
                        .addComponent(textoPreviewPreenchimentoCores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(previewCorPaleta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(previewCorPaleta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(previewCorPaleta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(previewCorPaleta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoPreviewPreenchimentoTextura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoPreviewCorFundo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previewCorFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(canvasPreviewFormaFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textoTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoTitulo.setText("Mosaico Fractal");

        menuEstampas.setText("Estampas");

        estampaAdicionar.setText("Adicionar...");
        estampaAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estampaAdicionarActionPerformed(evt);
            }
        });
        menuEstampas.add(estampaAdicionar);

        estampaSelecionar.setText("Selecionar...");
        estampaSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estampaSelecionarActionPerformed(evt);
            }
        });
        menuEstampas.add(estampaSelecionar);

        barraMenu.add(menuEstampas);

        menuPreenchimento.setText("Preenchimento");

        menuCores.setText("Cores");

        itemCoresSelecionar.setText("Selecionar...");
        menuCores.add(itemCoresSelecionar);

        menuPreenchimento.add(menuCores);

        menuTextura.setText("Textura");

        itemTexturaAdicionar.setText("Adicionar...");
        itemTexturaAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTexturaAdicionarActionPerformed(evt);
            }
        });
        menuTextura.add(itemTexturaAdicionar);

        itemTexturaSelecionar.setText("Selecionar...");
        menuTextura.add(itemTexturaSelecionar);

        menuPreenchimento.add(menuTextura);

        barraMenu.add(menuPreenchimento);

        menuAjuda.setText("Ajuda");

        itemManual.setText("Manual");
        menuAjuda.add(itemManual);

        itemSobre.setText("Sobre");
        menuAjuda.add(itemSobre);

        barraMenu.add(menuAjuda);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCorpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoTitulo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(textoTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCorpo, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioTelaFormaSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTelaFormaSimActionPerformed
        if (!radioBordaTelaSim.isSelected()){
            radioBordaTelaSim.setSelected(true);
        }
        if (radioTelaFormaSim.isSelected()) {
            if (radioRotacionarEstampasSim.isSelected()) {
                trocaIconeModo("modo_com_forma_sim_rotaciona");
            }
            else {
                trocaIconeModo("modo_com_forma_nao_rotaciona");
            }
        }
        textoPreviewFormaFundo.setText("Forma do fundo:");
        trocaIconeForma(forma_fundo);
    }//GEN-LAST:event_radioTelaFormaSimActionPerformed

    private void radioBordaTelaNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBordaTelaNaoActionPerformed
        if (!radioTelaFormaNao.isSelected()){
            radioTelaFormaNao.setSelected(true);
            textoPreviewFormaFundo.setText("Fundo normal.");
            deixaVazio(canvasPreviewFormaFundo);
        }
        if (radioBordaTelaNao.isSelected()) {
            if (radioRotacionarEstampasSim.isSelected()) {
                trocaIconeModo("modo_sem_forma_sim_rotaciona_sem_limite");
            }
            else {
                trocaIconeModo("modo_sem_forma_nao_rotaciona_sem_limite");
            }
        }
    }//GEN-LAST:event_radioBordaTelaNaoActionPerformed

    private void radioTelaFormaNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTelaFormaNaoActionPerformed
        if (radioTelaFormaNao.isSelected()) {
            if (radioRotacionarEstampasSim.isSelected()) {
                if (radioBordaTelaSim.isSelected()) {
                    trocaIconeModo("modo_sem_forma_sim_rotaciona_com_limite");
                }
                else {
                    trocaIconeModo("modo_sem_forma_sim_rotaciona_sem_limite");
                }
            }
            else {
                if (radioBordaTelaSim.isSelected()) {
                    trocaIconeModo("modo_sem_forma_nao_rotaciona_com_limite");
                }
                else {
                    trocaIconeModo("modo_sem_forma_nao_rotaciona_sem_limite");
                }
            }
        }
        textoPreviewFormaFundo.setText("Fundo normal.");
        deixaVazio(canvasPreviewFormaFundo);
    }//GEN-LAST:event_radioTelaFormaNaoActionPerformed

    private void radioTipoPreenchimentoCoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTipoPreenchimentoCoresActionPerformed
        if (!"Cores? Sim. Sendo elas:".equals(textoPreviewPreenchimentoCores.getText())){
            textoPreviewPreenchimentoCores.setText("Cores? Sim. Sendo elas:");
            textoPreviewPreenchimentoCores.setForeground(java.awt.Color.BLACK);
            
            previewCorPaleta1.setVisible(true);
            previewCorPaleta2.setVisible(true);
            previewCorPaleta3.setVisible(true);
            previewCorPaleta4.setVisible(true);
        }
        if ("Textura? Sim. Sendo ela:".equals(textoPreviewPreenchimentoTextura.getText())){
            textoPreviewPreenchimentoTextura.setText("Textura? Não.");
            textoPreviewPreenchimentoTextura.setForeground(java.awt.SystemColor.textInactiveText);
            deixaVazio(canvasPreviewPreenchimento);
        }
    }//GEN-LAST:event_radioTipoPreenchimentoCoresActionPerformed

    private void radioTipoPreenchimentoTexturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTipoPreenchimentoTexturasActionPerformed
        if ("Cores? Sim. Sendo elas:".equals(textoPreviewPreenchimentoCores.getText())){
            textoPreviewPreenchimentoCores.setText("Cores? Não.");
            textoPreviewPreenchimentoCores.setForeground(java.awt.SystemColor.textInactiveText);
            
            previewCorPaleta1.setVisible(false);
            previewCorPaleta2.setVisible(false);
            previewCorPaleta3.setVisible(false);
            previewCorPaleta4.setVisible(false);
        }
        if (!"Textura? Sim. Sendo ela:".equals(textoPreviewPreenchimentoTextura.getText())){
            textoPreviewPreenchimentoTextura.setText("Textura? Sim. Sendo ela:");
            textoPreviewPreenchimentoTextura.setForeground(java.awt.Color.BLACK);
        }
        
        trocaIconeTextura(textura);
    }//GEN-LAST:event_radioTipoPreenchimentoTexturasActionPerformed

    private void radioBordaTelaSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBordaTelaSimActionPerformed
        if (radioBordaTelaSim.isSelected()) {
            if (radioTelaFormaSim.isSelected()) {
                if (radioRotacionarEstampasSim.isSelected()) {
                    trocaIconeModo("modo_com_forma_sim_rotaciona");
                }
                else {
                    trocaIconeModo("modo_com_forma_nao_rotaciona");
                }
            }
            else {
                if (radioRotacionarEstampasSim.isSelected()) {
                    trocaIconeModo("modo_sem_forma_sim_rotaciona_com_limite");
                }
                else {
                    trocaIconeModo("modo_sem_forma_nao_rotaciona_com_limite");
                }
            }
        }
    }//GEN-LAST:event_radioBordaTelaSimActionPerformed

    private void radioRotacionarEstampasSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRotacionarEstampasSimActionPerformed
        if (radioRotacionarEstampasSim.isSelected()) {
            if (radioTelaFormaSim.isSelected()) {
                trocaIconeModo("modo_com_forma_sim_rotaciona");
            }
            else {
                if (radioBordaTelaSim.isSelected()) {
                    trocaIconeModo("modo_sem_forma_sim_rotaciona_com_limite");
                }
                else {
                    trocaIconeModo("modo_sem_forma_sim_rotaciona_sem_limite");
                }
            }
        }
    }//GEN-LAST:event_radioRotacionarEstampasSimActionPerformed

    private void radioRotacionarEstampasNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRotacionarEstampasNaoActionPerformed
        if (radioRotacionarEstampasNao.isSelected()) {
            if (radioTelaFormaSim.isSelected()) {
                trocaIconeModo("modo_com_forma_nao_rotaciona");
            }
            else {
                if (radioBordaTelaSim.isSelected()) {
                    trocaIconeModo("modo_sem_forma_nao_rotaciona_com_limite");
                }
                else {
                    trocaIconeModo("modo_sem_forma_nao_rotaciona_sem_limite");
                }
            }
        }
    }//GEN-LAST:event_radioRotacionarEstampasNaoActionPerformed

    private void estampaSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estampaSelecionarActionPerformed
        File folder = new File("src/mosaicofractal/arquivos/estampas");
        File[] lista_arquivos = folder.listFiles();
        ArrayList<String> nomes_arquivos = new ArrayList<>();
        for (File x : lista_arquivos) {
            if (x.isFile()) {
                nomes_arquivos.add(x.getName());
            }
        }
        Object [] valores = nomes_arquivos.toArray();
        Object valor_selecionado = JOptionPane.showInputDialog(this,
                "Selecione uma das Estampas abaixo", "Mosaico Fractal",
                JOptionPane.PLAIN_MESSAGE, null,
                valores, valores[0]);
    }//GEN-LAST:event_estampaSelecionarActionPerformed

    private void estampaAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estampaAdicionarActionPerformed
        int retorno = fileEstampaAdicionar.showOpenDialog(this);
        if (retorno == javax.swing.JFileChooser.APPROVE_OPTION){
            File arquivo = fileEstampaAdicionar.getSelectedFile();
            File copia;
            try {
                copia = new File("src/mosaicofractal/arquivos/estampas/estampa" + numeroEstampa() + ".svg").getCanonicalFile();
                Files.copy(arquivo.toPath(),copia.toPath(), REPLACE_EXISTING);
            } catch (IOException ex) {
                Logger.getLogger(InterfaceUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_estampaAdicionarActionPerformed

    private void itemTexturaAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTexturaAdicionarActionPerformed
        int retorno = filePreenchimentoAdicionar.showOpenDialog(this);
        if (retorno == javax.swing.JFileChooser.APPROVE_OPTION){
            File arquivo = filePreenchimentoAdicionar.getSelectedFile();
            File copia;
            try {
                copia = new File("src/mosaicofractal/arquivos/texturas/textura" + numeroTextura() + ".svg").getCanonicalFile();
                Files.copy(arquivo.toPath(),copia.toPath(), REPLACE_EXISTING);
            } catch (IOException ex) {
                Logger.getLogger(InterfaceUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_itemTexturaAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the default OS look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        }
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(InterfaceUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InterfaceUsuario().setVisible(true);
        });
    }
    
    public void trocaIconeModo(String arquivo) {
        try{
            File g = new File("src/mosaicofractal/gui/icones/" + arquivo + ".svg").getCanonicalFile();
            canvasPreviewModo.setURI(g.toURI().toString());
        }
        catch(java.io.IOException e){}
    }
    
    public void trocaIconeEstampa(int arquivo) {
        try{
            File g = new File("src/mosaicofractal/arquivos/estampas/estampa" + arquivo + ".svg").getCanonicalFile();
            canvasPreviewEstampa.setURI(g.toURI().toString());
        }
        catch(java.io.IOException e){}
    }
    
    public void trocaIconeTextura(int arquivo) {
        try{
            File g = new File("src/mosaicofractal/arquivos/texturas/textura" + arquivo + ".svg").getCanonicalFile();
            canvasPreviewPreenchimento.setURI(g.toURI().toString());
        }
        catch(java.io.IOException e){}
    }
    
    public void trocaIconeForma(int arquivo) {
        try{
            File g = new File("src/mosaicofractal/arquivos/estampas/estampa" + arquivo + ".svg").getCanonicalFile();
            canvasPreviewFormaFundo.setURI(g.toURI().toString());
        }
        catch(java.io.IOException e){}
    }
    
    public void deixaVazio(org.apache.batik.swing.JSVGCanvas canvas) {
        try{
            File g = new File("src/mosaicofractal/arquivos/vazio.svg").getCanonicalFile();
            canvas.setURI(g.toURI().toString());
        }
        catch(java.io.IOException e){}
    }
    
    private int numeroEstampa() {
        try {
            int v = 1;
            File salva = new File("src/mosaicofractal/arquivos/estampas/estampa" + v + ".svg").getCanonicalFile();
            while (salva.exists()){
                v++;
                salva = new File("src/mosaicofractal/arquivos/estampas/estampa" + v + ".svg").getCanonicalFile();
            }
            return v;
        } catch (IOException ex) {
            Logger.getLogger(InterfaceUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return 0;
    }
    
    private int numeroTextura(){
        try{
            int v = 1;
            File salva = new File("src/mosaicofractal/arquivos/texturas/textura" + v + ".svg").getCanonicalFile();
            while (salva.exists()){
                v++;
                salva = new File("src/mosaicofractal/arquivos/texturas/textura" + v + ".svg").getCanonicalFile();
            }
            return v;
        } catch (IOException ex) {
            Logger.getLogger(InterfaceUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return 0;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botaoEstampaExcluir;
    private javax.swing.JButton botaoEstampaSelecionar;
    private javax.swing.JButton botaoFrameCoresEstampaApagar;
    private javax.swing.JButton botaoFrameCoresEstampaSelecionar;
    private javax.swing.JButton botaoFrameCoresFundoSelecionar;
    private javax.swing.JButton botaoIniciar;
    private javax.swing.JButton botaoTexturaExcluir;
    private javax.swing.JButton botaoTexturaSelecionar;
    private javax.swing.ButtonGroup buttonGroupBordaTela;
    private javax.swing.ButtonGroup buttonGroupRotacionarEstampas;
    private javax.swing.ButtonGroup buttonGroupTelaForma;
    private javax.swing.ButtonGroup buttonGroupTipoPreenchimento;
    private org.apache.batik.swing.JSVGCanvas canvasPreviewEstampa;
    private org.apache.batik.swing.JSVGCanvas canvasPreviewFormaFundo;
    private org.apache.batik.swing.JSVGCanvas canvasPreviewModo;
    private org.apache.batik.swing.JSVGCanvas canvasPreviewPreenchimento;
    private org.apache.batik.swing.JSVGCanvas canvasframeEstampa;
    private org.apache.batik.swing.JSVGCanvas canvasframeTextura;
    private javax.swing.JComboBox<String> comboboxEstampas;
    private javax.swing.JComboBox<String> comboboxTexturas;
    private javax.swing.JColorChooser escolherCor;
    private javax.swing.JMenuItem estampaAdicionar;
    private javax.swing.JMenuItem estampaSelecionar;
    private javax.swing.JFileChooser fileEstampaAdicionar;
    private javax.swing.JFileChooser filePreenchimentoAdicionar;
    private javax.swing.JFrame frameCoresEscolher;
    private javax.swing.JFrame frameEstampaEscolher;
    private javax.swing.JFrame frameTexturasEscolher;
    private javax.swing.JMenuItem itemCoresSelecionar;
    private javax.swing.JMenuItem itemManual;
    private javax.swing.JMenuItem itemSobre;
    private javax.swing.JMenuItem itemTexturaAdicionar;
    private javax.swing.JMenuItem itemTexturaSelecionar;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuCores;
    private javax.swing.JMenu menuEstampas;
    private javax.swing.JMenu menuPreenchimento;
    private javax.swing.JMenu menuTextura;
    private javax.swing.JPanel panelCorpo;
    private javax.swing.JPanel panelFrameCoresEstampa1;
    private javax.swing.JPanel panelFrameCoresEstampa2;
    private javax.swing.JPanel panelFrameCoresEstampa3;
    private javax.swing.JPanel panelFrameCoresEstampa4;
    private javax.swing.JPanel panelFrameCoresFundo;
    private javax.swing.JSeparator panelSeparador;
    private javax.swing.JPanel previewCorFundo;
    private javax.swing.JPanel previewCorPaleta1;
    private javax.swing.JPanel previewCorPaleta2;
    private javax.swing.JPanel previewCorPaleta3;
    private javax.swing.JPanel previewCorPaleta4;
    private javax.swing.JRadioButton radioBordaTelaNao;
    private javax.swing.JRadioButton radioBordaTelaSim;
    private javax.swing.JRadioButton radioRotacionarEstampasNao;
    private javax.swing.JRadioButton radioRotacionarEstampasSim;
    private javax.swing.JRadioButton radioTelaFormaNao;
    private javax.swing.JRadioButton radioTelaFormaSim;
    private javax.swing.JRadioButton radioTipoPreenchimentoCores;
    private javax.swing.JRadioButton radioTipoPreenchimentoTexturas;
    private javax.swing.JSpinner spinnerValorC;
    private javax.swing.JLabel textoBordaTela;
    private javax.swing.JLabel textoFrameCoresCorpo;
    private javax.swing.JLabel textoFrameCoresEstampas;
    private javax.swing.JLabel textoFrameCoresFundo;
    private javax.swing.JLabel textoFrameEstampaCorpo;
    private javax.swing.JLabel textoFrameEstampaPreview;
    private javax.swing.JLabel textoFrameTexturaCorpo;
    private javax.swing.JLabel textoFrameTexturaPreview;
    private javax.swing.JLabel textoPreview;
    private javax.swing.JLabel textoPreviewCorFundo;
    private javax.swing.JLabel textoPreviewEstampa;
    private javax.swing.JLabel textoPreviewFormaFundo;
    private javax.swing.JLabel textoPreviewModo;
    private javax.swing.JLabel textoPreviewPreenchimento;
    private javax.swing.JLabel textoPreviewPreenchimentoCores;
    private javax.swing.JLabel textoPreviewPreenchimentoTextura;
    private javax.swing.JLabel textoRotacionarEstampas;
    private javax.swing.JLabel textoTelaForma;
    private javax.swing.JLabel textoTipoPreenchimento;
    private javax.swing.JLabel textoTitulo;
    private javax.swing.JLabel textoValorC;
    // End of variables declaration//GEN-END:variables
}
